name: "Bug report"
description: "Report a reproducible problem"
title: "[bug]: "
labels: ["bug", "status:needs-triage"]
assignees: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Preliminary checks
      options:
        - label: I searched existing issues and Discussions.
          required: true
        - label: I can reproduce this on the latest release.
          required: true
  - type: input
    id: version
    attributes:
      label: Tool version
      description: Output of `claudecode-git-checkpoints --version`
      placeholder: "e.g., 0.5.1"
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, shell, CPU arch, and Git version (`git --version`)
      placeholder: "macOS 14.5 (arm64), zsh 5.9, git 2.44.0"
    validations:
      required: true
  - type: dropdown
    id: install
    attributes:
      label: Install method
      options:
        - Homebrew
        - Prebuilt binary
        - Built from source
        - Other (describe below)
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: The minimal, precise steps. Include a tiny repo or script if possible.
      placeholder: |
        1. ...
        2. ...
        3. Observe error ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and debug output
      description: Run with `--debug` and attach relevant lines; redact secrets.
      render: text
  - type: input
    id: repro-link
    attributes:
      label: Minimal reproduction repo or gist
      placeholder: "https://github.com/<you>/<min-repro>"
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or terminal capture
      description: Optional, but very helpful
