name: "Feature request"
description: "Propose an enhancement or new capability"
title: "[feature]: "
labels: ["feature", "status:needs-triage"]
assignees: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Preliminary checks
      options:
        - label: I searched existing issues and Discussions.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem are you trying to solve?
      placeholder: "When I..., I want..., so that..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behavior or API/CLI shape.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you tried or considered.
  - type: dropdown
    id: impact
    attributes:
      label: Impact / priority
      options:
        - nice to have
        - important
        - blocking
    validations:
      required: true
  - type: input
    id: area
    attributes:
      label: Affected area (if known)
      placeholder: "CLI | docs | git-integration | performance | other"
  - type: textarea
    id: extras
    attributes:
      label: Additional context
      description: Links, sketches, examples
